name: network_state_manager
description: A Flutter package for managing network states and exceptions.
version: 0.0.1
homepage: https://github.com/yourusername/network_state_manager


environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7

flutter:

